openapi: 3.0.0
info:
  title: AVKysynMieheltä
  version: '1.0'
  description: AV Kysyn mieheltä is a webshop
  contact:
    name: OssiH
    email: heino@ruojasol.fi
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{userId}':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        '404':
          description: User Not Found
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
    patch:
      summary: Update User Information
      operationId: patch-users-userId
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Updated User Rebecca Baker:
                  value:
                    id: 13
                    firstName: Rebecca
                    lastName: Baker
                    email: rebecca@gmail.com
                    dateOfBirth: '1985-10-02'
                    emailVerified: false
                    createDate: '2019-08-24'
        '404':
          description: User Not Found
        '409':
          description: Email Already Taken
      description: Update the infromation of an existing user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  description: 'If a new email is given, the user''s email verified property will be set to false.'
                dateOfBirth:
                  type: string
            examples:
              Update First Name:
                value:
                  firstName: Rebecca
              Update Email:
                value:
                  email: rebecca@gmail.com
              Update Last Name & Date of Birth:
                value:
                  lastName: Baker
                  dateOfBirth: '1985-10-02'
        description: Patch user properties to update.
    put:
      summary: ''
      operationId: put-users-userId
      responses:
        '200':
          description: OK
      description: Update user
    delete:
      summary: ''
      operationId: delete-users-userId
      responses:
        '200':
          description: OK
      description: Delete the user
  /user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              $ref: ''
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
  /items:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-items
      description: Gets items being sold
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Items'
            examples: {}
        description: ''
    post:
      summary: ''
      operationId: post-items
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Items'
              examples: {}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorReason:
                    type: string
      description: Create a new item
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Items'
            examples: {}
    put:
      summary: ''
      operationId: put-items
      responses:
        '200':
          description: OK
  '/items/{itemId}':
    parameters:
      - schema:
          type: string
        name: itemId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '404':
          description: Item not found
      operationId: get-items-itemId
      description: Gets information of a single item
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Items'
    delete:
      summary: ''
      operationId: delete-items-itemId
      responses:
        '202':
          description: Accepted
        '404':
          description: Item not found
      description: Delete single item
    patch:
      summary: ''
      operationId: patch-items-itemId
      responses:
        '200':
          description: OK
    put:
      summary: ''
      operationId: put-items-itemId
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      x-examples:
        Alice Smith:
          id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
        userName:
          type: string
        password:
          type: string
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
    Items:
      title: Items
      type: object
      description: ''
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        category:
          type: string
        askingPrice:
          type: number
        dateOfPosting:
          type: string
        deliveryType:
          type: string
        contactInformation:
          type: object
          properties:
            sellerId:
              type: integer
            address:
              type: string
            postalCode:
              type: integer
            city:
              type: string
            country:
              type: string
